import { prisma } from '@/lib/db';

// Demo applications for /api/auth/demo and /api/demo/seed
// (a similar set lives in prisma/seed.js for CLI `db:seed`)
const MOCK_APPS = [
  {
    vacancyName: 'Frontend Developer (React)',
    employerName: 'Яндекс',
    areaName: 'Москва',
    status: 'invite',
    salaryFrom: 250000,
    salaryTo: 350000,
    daysAgo: 1,
    hour: 10,
  },
  {
    vacancyName: 'Middle Frontend Engineer',
    employerName: 'Тинькофф',
    areaName: 'Москва',
    status: 'interview',
    salaryFrom: 220000,
    salaryTo: 300000,
    daysAgo: 2,
    hour: 14,
  },
  {
    vacancyName: 'React-разработчик',
    employerName: 'Авито',
    areaName: 'Санкт-Петербург',
    status: 'viewed',
    salaryFrom: 200000,
    daysAgo: 3,
    hour: 11,
  },
  {
    vacancyName: 'Frontend Developer',
    employerName: 'Сбер',
    areaName: 'Москва',
    status: 'reject',
    salaryFrom: 180000,
    salaryTo: 250000,
    daysAgo: 4,
    hour: 16,
  },
  {
    vacancyName: 'Senior Frontend (Next.js)',
    employerName: 'OZON',
    areaName: 'Москва',
    status: 'sent',
    salaryFrom: 300000,
    salaryTo: 400000,
    daysAgo: 5,
    hour: 9,
  },
  {
    vacancyName: 'Frontend-разработчик',
    employerName: 'VK',
    areaName: 'Москва',
    status: 'invite',
    salaryFrom: 280000,
    daysAgo: 6,
    hour: 13,
  },
  {
    vacancyName: 'Web Developer',
    employerName: 'Wildberries',
    areaName: 'Москва',
    status: 'viewed',
    salaryFrom: 200000,
    salaryTo: 280000,
    daysAgo: 7,
    hour: 15,
  },
  {
    vacancyName: 'Frontend Engineer',
    employerName: 'Kaspersky',
    areaName: 'Москва',
    status: 'reject',
    daysAgo: 8,
    hour: 12,
  },
  {
    vacancyName: 'React Native Developer',
    employerName: 'МТС',
    areaName: 'Москва',
    status: 'sent',
    salaryFrom: 220000,
    salaryTo: 290000,
    daysAgo: 9,
    hour: 17,
  },
  {
    vacancyName: 'Junior+/Middle Frontend',
    employerName: 'Selectel',
    areaName: 'Санкт-Петербург',
    status: 'interview',
    salaryFrom: 150000,
    salaryTo: 200000,
    daysAgo: 10,
    hour: 11,
  },
  {
    vacancyName: 'Frontend Developer TypeScript',
    employerName: 'JetBrains',
    areaName: 'Санкт-Петербург',
    status: 'invite',
    salaryFrom: 280000,
    salaryTo: 380000,
    daysAgo: 11,
    hour: 10,
  },
  {
    vacancyName: 'UI Engineer',
    employerName: 'Lamoda',
    areaName: 'Москва',
    status: 'reject',
    salaryFrom: 180000,
    daysAgo: 12,
    hour: 14,
  },
  {
    vacancyName: 'Frontend Developer',
    employerName: 'X5 Digital',
    areaName: 'Москва',
    status: 'viewed',
    salaryFrom: 200000,
    salaryTo: 270000,
    daysAgo: 13,
    hour: 9,
  },
  {
    vacancyName: 'React Developer',
    employerName: 'Домклик',
    areaName: 'Москва',
    status: 'sent',
    daysAgo: 14,
    hour: 16,
  },
  {
    vacancyName: 'Middle Frontend (Vue/React)',
    employerName: 'Ростелеком',
    areaName: 'Екатеринбург',
    status: 'reject',
    salaryFrom: 160000,
    salaryTo: 220000,
    daysAgo: 15,
    hour: 12,
  },
  {
    vacancyName: 'Frontend-разработчик в команду поиска',
    employerName: 'Яндекс',
    areaName: 'Москва',
    status: 'interview',
    salaryFrom: 260000,
    salaryTo: 340000,
    daysAgo: 16,
    hour: 11,
  },
  {
    vacancyName: 'Web Frontend Engineer',
    employerName: 'Тинькофф',
    areaName: 'Москва',
    status: 'sent',
    salaryFrom: 240000,
    daysAgo: 18,
    hour: 15,
  },
  {
    vacancyName: 'Frontend Developer',
    employerName: 'Альфа-Банк',
    areaName: 'Москва',
    status: 'viewed',
    salaryFrom: 210000,
    salaryTo: 290000,
    daysAgo: 20,
    hour: 10,
  },
  {
    vacancyName: 'Senior Frontend Developer',
    employerName: 'Avito Tech',
    areaName: 'Москва',
    status: 'invite',
    salaryFrom: 320000,
    salaryTo: 420000,
    daysAgo: 22,
    hour: 13,
  },
  {
    vacancyName: 'Frontend (React + GraphQL)',
    employerName: 'OZON',
    areaName: 'Москва',
    status: 'offer',
    salaryFrom: 300000,
    daysAgo: 25,
    hour: 9,
  },
  {
    vacancyName: 'Frontend Developer',
    employerName: 'ЦБ РФ',
    areaName: 'Москва',
    status: 'reject',
    daysAgo: 27,
    hour: 14,
  },
  {
    vacancyName: 'React-разработчик',
    employerName: 'Skillbox',
    areaName: 'Москва',
    isRemote: true,
    status: 'sent',
    salaryFrom: 180000,
    salaryTo: 240000,
    daysAgo: 0,
    hour: 19,
  },
  {
    vacancyName: 'Middle Frontend',
    employerName: 'Tochka',
    areaName: 'Москва',
    status: 'viewed',
    salaryFrom: 230000,
    salaryTo: 300000,
    daysAgo: 1,
    hour: 8,
  },
  {
    vacancyName: 'Frontend Engineer',
    employerName: '2GIS',
    areaName: 'Новосибирск',
    status: 'interview',
    salaryFrom: 200000,
    daysAgo: 3,
    hour: 12,
  },
  {
    vacancyName: 'Junior Frontend Developer',
    employerName: 'Skyeng',
    areaName: 'Москва',
    status: 'sent',
    salaryFrom: 120000,
    salaryTo: 160000,
    daysAgo: 0,
    hour: 11,
  },
  {
    vacancyName: 'Vue.js Developer',
    employerName: 'Нетология',
    areaName: 'Москва',
    status: 'viewed',
    salaryFrom: 200000,
    salaryTo: 280000,
    daysAgo: 2,
    hour: 15,
  },
  {
    vacancyName: 'Frontend (React/Redux)',
    employerName: 'Delivery Club',
    areaName: 'Москва',
    status: 'invite',
    salaryFrom: 220000,
    daysAgo: 4,
    hour: 10,
  },
  {
    vacancyName: 'Middle Frontend Engineer',
    employerName: 'Совкомбанк',
    areaName: 'Москва',
    status: 'interview',
    salaryFrom: 210000,
    salaryTo: 290000,
    daysAgo: 5,
    hour: 14,
  },
  {
    vacancyName: 'React Developer',
    employerName: 'ЮMoney',
    areaName: 'Москва',
    status: 'offer',
    salaryFrom: 250000,
    salaryTo: 320000,
    daysAgo: 6,
    hour: 9,
  },
  {
    vacancyName: 'Frontend-разработчик',
    employerName: 'Газпромбанк',
    areaName: 'Москва',
    status: 'reject',
    salaryFrom: 190000,
    salaryTo: 260000,
    daysAgo: 7,
    hour: 16,
  },
  {
    vacancyName: 'Senior React Developer',
    employerName: 'Т-Банк',
    areaName: 'Москва',
    status: 'sent',
    salaryFrom: 350000,
    salaryTo: 450000,
    daysAgo: 8,
    hour: 12,
  },
  {
    vacancyName: 'Frontend Developer (TypeScript)',
    employerName: 'Positive Technologies',
    areaName: 'Москва',
    status: 'viewed',
    salaryFrom: 240000,
    daysAgo: 9,
    hour: 11,
  },
  {
    vacancyName: 'UI Developer',
    employerName: 'Okko',
    areaName: 'Санкт-Петербург',
    status: 'invite',
    salaryFrom: 200000,
    salaryTo: 270000,
    daysAgo: 10,
    hour: 13,
  },
  {
    vacancyName: 'Frontend Engineer',
    employerName: 'Wrike',
    areaName: 'Москва',
    isRemote: true,
    status: 'interview',
    salaryFrom: 280000,
    salaryTo: 360000,
    daysAgo: 11,
    hour: 10,
  },
  {
    vacancyName: 'Middle Frontend (React)',
    employerName: 'Qiwi',
    areaName: 'Москва',
    status: 'offer',
    salaryFrom: 230000,
    daysAgo: 12,
    hour: 15,
  },
  {
    vacancyName: 'React Native Engineer',
    employerName: 'МегаФон',
    areaName: 'Москва',
    status: 'reject',
    daysAgo: 13,
    hour: 9,
  },
  {
    vacancyName: 'Frontend Developer',
    employerName: 'ivi',
    areaName: 'Москва',
    status: 'sent',
    salaryFrom: 210000,
    salaryTo: 290000,
    daysAgo: 14,
    hour: 17,
  },
  {
    vacancyName: 'Vue Frontend Developer',
    employerName: 'Билайн',
    areaName: 'Москва',
    status: 'viewed',
    salaryFrom: 180000,
    salaryTo: 240000,
    daysAgo: 15,
    hour: 11,
  },
  {
    vacancyName: 'Senior Frontend (Next.js)',
    employerName: 'Циан',
    areaName: 'Москва',
    status: 'invite',
    salaryFrom: 300000,
    salaryTo: 400000,
    daysAgo: 16,
    hour: 14,
  },
  {
    vacancyName: 'Frontend-разработчик',
    employerName: 'HeadHunter',
    areaName: 'Москва',
    status: 'interview',
    salaryFrom: 250000,
    salaryTo: 330000,
    daysAgo: 17,
    hour: 10,
  },
  {
    vacancyName: 'React Developer',
    employerName: 'ВТБ',
    areaName: 'Москва',
    status: 'offer',
    salaryFrom: 260000,
    daysAgo: 18,
    hour: 12,
  },
  {
    vacancyName: 'Middle Frontend Engineer',
    employerName: 'Райффайзенбанк',
    areaName: 'Москва',
    status: 'reject',
    salaryFrom: 220000,
    salaryTo: 300000,
    daysAgo: 19,
    hour: 16,
  },
  {
    vacancyName: 'Frontend Developer',
    employerName: 'М.Видео',
    areaName: 'Москва',
    status: 'sent',
    daysAgo: 20,
    hour: 9,
  },
  {
    vacancyName: 'Web Engineer (React)',
    employerName: 'DNS',
    areaName: 'Владивосток',
    status: 'viewed',
    salaryFrom: 170000,
    salaryTo: 230000,
    daysAgo: 21,
    hour: 13,
  },
  {
    vacancyName: 'Frontend (React + TypeScript)',
    employerName: 'Хоум Банк',
    areaName: 'Москва',
    status: 'invite',
    salaryFrom: 200000,
    salaryTo: 280000,
    daysAgo: 22,
    hour: 11,
  },
  {
    vacancyName: 'Junior+/Middle Frontend',
    employerName: 'Uzum',
    areaName: 'Москва',
    isRemote: true,
    status: 'interview',
    salaryFrom: 150000,
    salaryTo: 210000,
    daysAgo: 23,
    hour: 15,
  },
  {
    vacancyName: 'Senior Frontend Developer',
    employerName: 'СберМегаМаркет',
    areaName: 'Москва',
    status: 'offer',
    salaryFrom: 320000,
    salaryTo: 420000,
    daysAgo: 24,
    hour: 10,
  },
  {
    vacancyName: 'React-разработчик',
    employerName: 'МойСклад',
    areaName: 'Москва',
    status: 'reject',
    salaryFrom: 190000,
    daysAgo: 26,
    hour: 14,
  },
  {
    vacancyName: 'Frontend Developer',
    employerName: 'Контур',
    areaName: 'Екатеринбург',
    status: 'sent',
    salaryFrom: 180000,
    salaryTo: 250000,
    daysAgo: 28,
    hour: 9,
  },
  {
    vacancyName: 'UI Engineer (React)',
    employerName: 'Naverisk',
    areaName: 'Санкт-Петербург',
    status: 'viewed',
    salaryFrom: 220000,
    salaryTo: 300000,
    daysAgo: 29,
    hour: 12,
  },
  {
    vacancyName: 'Frontend Engineer',
    employerName: 'OCS',
    areaName: 'Москва',
    status: 'invite',
    daysAgo: 30,
    hour: 11,
  },
  {
    vacancyName: 'Middle Frontend (Vue 3)',
    employerName: 'Ситилинк',
    areaName: 'Москва',
    status: 'interview',
    salaryFrom: 170000,
    salaryTo: 230000,
    daysAgo: 31,
    hour: 16,
  },
  {
    vacancyName: 'React Developer',
    employerName: 'Касперский',
    areaName: 'Москва',
    status: 'offer',
    salaryFrom: 270000,
    salaryTo: 350000,
    daysAgo: 32,
    hour: 10,
  },
  {
    vacancyName: 'Frontend-разработчик',
    employerName: 'Леруа Мерлен',
    areaName: 'Москва',
    status: 'reject',
    salaryFrom: 160000,
    salaryTo: 220000,
    daysAgo: 33,
    hour: 13,
  },
  {
    vacancyName: 'Senior Frontend (React)',
    employerName: 'Яндекс Маркет',
    areaName: 'Москва',
    status: 'sent',
    salaryFrom: 330000,
    salaryTo: 430000,
    daysAgo: 34,
    hour: 9,
  },
  {
    vacancyName: 'Frontend Developer TypeScript',
    employerName: 'Тинькофф Образование',
    areaName: 'Москва',
    status: 'viewed',
    salaryFrom: 200000,
    daysAgo: 35,
    hour: 15,
  },
  {
    vacancyName: 'React Native Developer',
    employerName: 'Банки.ру',
    areaName: 'Москва',
    status: 'invite',
    salaryFrom: 230000,
    salaryTo: 310000,
    daysAgo: 36,
    hour: 11,
  },
  {
    vacancyName: 'Frontend Engineer',
    employerName: 'Финтех Лаб',
    areaName: 'Казань',
    status: 'interview',
    salaryFrom: 180000,
    salaryTo: 250000,
    daysAgo: 37,
    hour: 14,
  },
  {
    vacancyName: 'Middle Frontend Developer',
    employerName: 'CloudPayments',
    areaName: 'Москва',
    isRemote: true,
    status: 'offer',
    salaryFrom: 240000,
    salaryTo: 320000,
    daysAgo: 38,
    hour: 10,
  },
  {
    vacancyName: 'Frontend (Next.js + GraphQL)',
    employerName: 'Rubetek',
    areaName: 'Москва',
    status: 'reject',
    daysAgo: 39,
    hour: 12,
  },
  {
    vacancyName: 'Web Frontend Developer',
    employerName: 'Додо Пицца',
    areaName: 'Сыктывкар',
    isRemote: true,
    status: 'sent',
    salaryFrom: 160000,
    salaryTo: 220000,
    daysAgo: 40,
    hour: 9,
  },
  {
    vacancyName: 'React-разработчик',
    employerName: 'Сравни.ру',
    areaName: 'Москва',
    status: 'viewed',
    salaryFrom: 210000,
    salaryTo: 280000,
    daysAgo: 41,
    hour: 16,
  },
  {
    vacancyName: 'Senior Frontend Engineer',
    employerName: 'X5 Tech',
    areaName: 'Москва',
    status: 'invite',
    salaryFrom: 310000,
    salaryTo: 410000,
    daysAgo: 42,
    hour: 11,
  },
  {
    vacancyName: 'Frontend Developer',
    employerName: 'Аптечная сеть 36,6',
    areaName: 'Москва',
    status: 'interview',
    salaryFrom: 150000,
    daysAgo: 43,
    hour: 13,
  },
  {
    vacancyName: 'UI Developer (React)',
    employerName: 'ManyChat',
    areaName: 'Москва',
    isRemote: true,
    status: 'offer',
    salaryFrom: 280000,
    salaryTo: 380000,
    daysAgo: 44,
    hour: 10,
  },
  {
    vacancyName: 'Middle Frontend',
    employerName: 'Онлайн Патент',
    areaName: 'Москва',
    status: 'reject',
    salaryFrom: 170000,
    salaryTo: 230000,
    daysAgo: 45,
    hour: 15,
  },
  {
    vacancyName: 'Frontend Engineer (Vue)',
    employerName: 'Тензор',
    areaName: 'Ярославль',
    status: 'sent',
    salaryFrom: 160000,
    salaryTo: 220000,
    daysAgo: 4,
    hour: 8,
  },
  {
    vacancyName: 'React Developer',
    employerName: 'Gett',
    areaName: 'Москва',
    status: 'viewed',
    salaryFrom: 220000,
    daysAgo: 8,
    hour: 17,
  },
  {
    vacancyName: 'Frontend-разработчик в дизайн-систему',
    employerName: 'Альфа-Банк',
    areaName: 'Москва',
    status: 'invite',
    salaryFrom: 270000,
    salaryTo: 350000,
    daysAgo: 12,
    hour: 11,
  },
  {
    vacancyName: 'Senior Frontend (React + Zustand)',
    employerName: 'VK',
    areaName: 'Санкт-Петербург',
    status: 'interview',
    salaryFrom: 300000,
    salaryTo: 400000,
    daysAgo: 18,
    hour: 14,
  },
  {
    vacancyName: 'Frontend Developer',
    employerName: 'Ozon Tech',
    areaName: 'Казань',
    status: 'offer',
    salaryFrom: 250000,
    salaryTo: 340000,
    daysAgo: 25,
    hour: 9,
  },
  {
    vacancyName: 'Junior Frontend (React)',
    employerName: 'Яндекс Практикум',
    areaName: 'Москва',
    isRemote: true,
    status: 'reject',
    salaryFrom: 100000,
    salaryTo: 140000,
    daysAgo: 1,
    hour: 19,
  },
  {
    vacancyName: 'Frontend Engineer',
    employerName: 'Stripe (CIS)',
    areaName: 'Москва',
    isRemote: true,
    status: 'sent',
    salaryFrom: 350000,
    salaryTo: 500000,
    daysAgo: 27,
    hour: 12,
  },
  {
    vacancyName: 'Middle+/Senior Frontend',
    employerName: 'Авито',
    areaName: 'Екатеринбург',
    status: 'viewed',
    salaryFrom: 280000,
    salaryTo: 380000,
    daysAgo: 35,
    hour: 10,
  },
] as const;

function daysAgoDate(days: number, hour: number) {
  const d = new Date();
  d.setDate(d.getDate() - days);
  // Small minute jitter so timestamps are not identical to the second
  d.setHours(hour, 15 + (days % 40), 0, 0);
  return d;
}

// Replaces all of the user's applications with demo data
export async function seedDemoApplications(userId: number) {
  await prisma.application.deleteMany({ where: { userId } });

  for (let i = 0; i < MOCK_APPS.length; i += 1) {
    const item = MOCK_APPS[i];
    await prisma.application.create({
      data: {
        userId,
        externalId: `demo-${i + 1}`,
        vacancyId: `vac-${1000 + i}`,
        vacancyName: item.vacancyName,
        vacancyUrl: `https://hh.ru/vacancy/${1000 + i}`,
        employerId: `emp-${i}`,
        employerName: item.employerName,
        areaName: item.areaName,
        isRemote: 'isRemote' in item ? Boolean(item.isRemote) : false,
        salaryFrom: 'salaryFrom' in item ? (item.salaryFrom as number) : null,
        salaryTo: 'salaryTo' in item ? (item.salaryTo as number) : null,
        salaryCurrency: 'salaryFrom' in item ? 'RUR' : null,
        salaryGross: 'salaryFrom' in item ? false : null,
        status: item.status,
        appliedAt: daysAgoDate(item.daysAgo, item.hour),
        notes: null,
      },
    });
  }

  return MOCK_APPS.length;
}
